apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myemp
  namespace: default
  labels:
    app: myemp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myemp
      version: v1
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: myemp
        version: v1
    spec:
      containers:
      - name: myemp
        image: ernesen/icp-tech-talks #mycluster.icp:8500/ernesen/icp-tech-talks 
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent #Always #IfNotPresent
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1